"""Check authored Blender vegetation structure and generated FBX/render outputs."""
import json
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "Tools/Blender/generate_r6_vegetation_kit.py"
ASSETS = ROOT / "ArtSource/Vegetation/R6"
REPORT = ASSETS / "R6_VEGETATION_KIT_REPORT.json"
PREVIEW = ROOT / "ArtSource/Previews/R6_Vegetation_Kit_Blender.png"
EXPECTED_SPECIES = {"palmeira_copacabana", "arvore_tropical_ampla", "arvore_tropical_densa", "arbusto_tropical"}


class R6VegetationKitTests(unittest.TestCase):
    def test_authored_generator_has_tapered_organic_meshes_material_nodes_and_three_lods(self):
        source = SCRIPT.read_text(encoding="utf-8")
        for marker in ("append_tube", "append_leaf", "Principled BSDF", "LOD0", "LOD1", "LOD2",
                       "palmeira_copacabana", "arvore_tropical_ampla", "arvore_tropical_densa", "arbusto_tropical"):
            self.assertIn(marker, source)
        self.assertNotIn("primitive_cylinder_add", source)
        self.assertNotIn("primitive_uv_sphere_add", source)

    def test_generated_blend_fbx_and_real_render_report(self):
        if not REPORT.is_file():
            self.skipTest("Artifacts are generated by the dedicated Blender workflow; bpy/Blender is absent locally")
        report = json.loads(REPORT.read_text(encoding="utf-8"))
        self.assertEqual(report["status"], "R6_BLENDER_AUTHORED_SPECIES_KIT")
        self.assertEqual({x["id"] for x in report["species"]}, EXPECTED_SPECIES)
        self.assertTrue(all({x["name"] for x in species["lods"]} == {"LOD0", "LOD1", "LOD2"}
                            for species in report["species"]))
        blend = ASSETS / "R6_Vegetation_Kit.blend"
        self.assertTrue(blend.is_file() and blend.stat().st_size > 100_000)
        self.assertEqual(len(report["exports"]), 4)
        for export in report["exports"]:
            path = ROOT / export["path"]
            self.assertTrue(path.is_file())
            self.assertTrue(path.read_bytes().startswith(b"Kaydara FBX Binary"))
            self.assertTrue(export["binary_fbx"])
            self.assertLess(path.stat().st_size, 8_000_000)
        self.assertTrue(PREVIEW.is_file() and PREVIEW.stat().st_size > 100_000)
        self.assertEqual(report["renderer"], "Blender Cycles CPU")


if __name__ == "__main__":
    unittest.main()
